name: Perl CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: "5.38"
    - run: cpanm --installdeps .
    #- run: prove -lv t
    - run: perl Makefile.PL
    - run: make test
    #- run: cover -test -report coveralls
